services:

  postgres_configs-img:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: gamedream
      POSTGRES_USER: gamedream
      POSTGRES_MULTIPLE_DATABASES: accounts
      PGDATA: /var/lib/postgresql/data
    
    ports:
      - 20432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 200M

  nats-img:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--js"
    volumes:
      - nats:/data
    deploy:
      resources:
        limits:
          memory: 200M

  cache-img:
    image: redis/redis-stack:edge
    ports:
      - 16379:6379
    container_name: cache
    restart: always
    environment:
      REDIS_DATABASES: 3
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  postgres:
  nats: