version: '3.8'

services:

  postgres_configs:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_USER: psql9
      POSTGRES_MULTIPLE_DATABASES: accounts
      PGDATA: /var/lib/postgresql/data
    ports:
      - 20432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d

  nats-server-img:
    image: nats:latest
    container_name: nats-server-img
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats-server
      - NATS_MAX_CONNECTIONS=1000

volumes:
  postgres:
  nats-server:
