services:

  postgres_configs:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mbf
      POSTGRES_USER: mbf
      POSTGRES_MULTIPLE_DATABASES: users mails admin_api 
      PGDATA: /var/lib/postgresql/data
    
    ports:
      - 20432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--js"
    volumes:
      - nats:/data

  redis-cache:
    image: redis/redis-stack:edge
    ports:
      - 16379:6379
    container_name: redis-cache
    restart: always
    environment:
      REDIS_DATABASES: 3
      REDIS_PORT: 6379

volumes:
  postgres:
  nats: