apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-scripts
data:
  init.sql: |
    CREATE DATABASE users;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-configs
  labels:
    app: postgres-configs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-configs
  template:
    metadata:
      labels:
        app: postgres-configs
    spec:
      containers:
      - name: postgres-configs
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "mbf"
        - name: POSTGRES_USER
          value: "mbf"
        - name: PGDATA
          value: "/var/lib/postgresql/data"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: pg-init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: pg-init-scripts
        configMap:
          name: pg-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-configs
spec:
  selector:
    app: postgres-configs
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        args: ["--js"]
        ports:
        - containerPort: 4222
        - containerPort: 6222
        - containerPort: 8222
        volumeMounts:
        - name: nats-data
          mountPath: /data
      volumes:
      - name: nats-data
        persistentVolumeClaim:
          claimName: nats-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    protocol: TCP
    port: 4222
    targetPort: 4222
  - name: cluster
    protocol: TCP
    port: 6222
    targetPort: 6222
  - name: monitoring
    protocol: TCP
    port: 8222
    targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    app: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: redis/redis-stack:edge
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_DATABASES
          value: "3"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  selector:
    app: redis-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
