scalar JSON

type Mutation {
  Auth: AuthMutation
}

type Auth {
  _empty: String
}

input RegisterDto {
  username: String!
  email: String!
  password: String!
}

input LoginDto {
  username: String!
  password: String!
}

type TokenResponse {
  accessToken: String!
}

# -------------------------------------------------

type AuthMutation {
  register(data: RegisterDto!): Boolean!
  login(data: LoginDto!): TokenResponse!
}